PyPI distributed ``pup`` failed miserably because it did not include all of its own bundled templates -- now fixed.
